### PR TITLE
Simplify plugin and replace old menu

### PR DESCRIPTION
**Pull request by SubtypeZero**
I noticed that @vsddev implemented a fix for #5 and felt like I could further improve the plugin, so I spent some time cleaning things up. Most of the changes I have made were to simplify how the commands work, making it unnecessary to have one command class per color. With all of those changes and the removal of the menu, I believe this brings us to version 1.2 and makes the plugin much easier to use. The old menu was nice, but using a single command to change colors and toggle the effect makes it easier to find the color you want and avoids filling up your chat log. I have also spent some time testing these changes to make sure everything works. Here's a built jar of the new version: [PlayerGlow-Sponge-1.2.zip](https://github.com/MrHDR/Player_Glow_Sponge/files/1272000/PlayerGlow-Sponge-1.2.zip)

### CODE REVIEW

**Comment by SubtypeZero** [comment]
I realize you might be thinking that this changes too many things, but I hope you're willing to give it a shot because this seems like a major improvement to me

**Comment by SubtypeZero** [comment]
Oops, I accidentally closed the PR

**Comment by HDR** [comment]
Hi, thanks for the pull request, i'll take a look at this if i have some time later :)

**Comment by HDR** [comment]
Hi, sorry for taking a while to get back to you, haven't been active when it comes to minecraft, as it stands i don't really want to remove the chat menu, but i'm open to implementing your other changes.

**Comment by SubtypeZero** [comment]
There may be a couple issues that still need to be addressed (not sure if these changes are the cause), but that shouldn't be too difficult to fix. I think you'd like the menu replacement if you gave it a shot. Using `/glow` is much easier and doesn't spam up your chat history. The way I see it, it's not necessary to have a chat GUI when the plugin is super easy to use and you can tab complete the color argument for `/glow`.

**Pull request closed without merging**
